CREATE TABLE [dbo].[StkTrnDtls] (
	[TrnType] [int] NOT NULL ,
	[TrnCtrlNo] [int] NOT NULL ,
	[DocNoPrefix] [varchar] (8)   NOT NULL ,
	[DocNo] [int] NOT NULL ,
	[DocRsnCd] [varchar] (16)   NULL ,
	[DocDt] [datetime] NULL ,
	[EntSrlNo] [int] NOT NULL ,
	[StockNo] [varchar] (32)   NULL ,
	[BatchSrlNo] [varchar] (16)   NULL ,
	[LocnId] [varchar] (16)   NULL ,
	[OrdDocType] [int] NULL ,
	[OrdDocNoPrefix] [varchar] (8)   NULL ,
	[OrdDocNo] [int] NULL ,
	[OrdEntSrlNo] [int] NULL ,
	[OrdEntSubSrlNo] [int] NULL ,
	[RefDocType] [int] NULL ,
	[RefDocNoPrefix] [varchar] (8)   NULL ,
	[RefDocNo] [varchar] (32)   NULL ,
	[RefEntSrlNo] [int] NULL ,
	[DocQty] [real] NULL ,
	[PhyQtyIn] [real] NULL ,
	[PhyQtyOut] [real] NULL ,
	[StkUpdtRate] [money] NULL ,
	[StkUpdtValueIn] [money] NULL ,
	[StkUpdtValueOut] [money] NULL ,
	[DocEntRate] [money] NULL ,
	[DocEntValue] [money] NULL ,
	[DocEntTotDisc] [money] NULL ,
	[DocEntValAftDisc] [money] NULL ,
	[DocEntTax] [money] NULL ,
	[DocEntAddons] [money] NULL ,
	[DocEntDedns] [money] NULL ,
	[DocEntNetValue] [money] NULL ,
	[PhysQtyReturned] [real] NULL ,
	[DocEntBefTaxAddons] [money] NULL ,
	[DocEntBefTaxDedns] [money] NULL ,
	[DocEntAftTaxAddons] [money] NULL ,
	[DocEntAftTaxDedns] [money] NULL ,
	[DocEntDisc] [money] NULL ,
	[DocEntDiscId] [varchar] (32)   NULL ,
	[DocEntBillDisc] [money] NULL ,
	[DocEntVoidInd] [bit] NULL ,
	[ItemTaxType] [varchar] (16)   NULL ,
	[CustTaxType] [varchar] (16)   NULL ,
	[SrcTaxType] [varchar] (16)   NULL ,
	[TaxComp1] [money] NULL ,
	[TaxComp2] [money] NULL ,
	[TaxComp3] [money] NULL ,
	[TaxComp4] [money] NULL ,
	[TaxComp5] [money] NULL ,
	[RetnReasonCd] [varchar] (16)   NULL ,
	[FwdRefTrnType] [int] NULL ,
	[FwdRefCtrlNo] [int] NULL ,
	[FwdRefDocEntSrlNo] [int] NULL ,
	[BackRefTrnType] [int] NULL ,
	[BackRefCtrlNo] [int] NULL ,
	[BackRefDocEntSrlNo] [int] NULL ,
	[BillPassInd] [int] NULL ,
	[VAUid] [varchar] (32)   NULL ,
	[VActr] [int] NULL ,
	[VATermId] [varchar] (32)   NULL ,
	[VACompCode] [varchar] (16)   NULL ,
	[SalesPersonCd] [varchar] (32)   NULL ,
	[ItemwiseDiscReason] [varchar] (250)   NULL ,
	[ExptTrnType] [int] NULL ,
	[ExptTrnDocPfx] [varchar] (16)   NULL ,
	[ExptTrnDocNo] [int] NULL ,
	[ExptTrnDocSrlNo] [int] NULL ,
	[ExptTrnDocSubSrlNo] [int] NULL ,
	[EUPCode] [varchar] (50)   NULL ,
	[ApplPoint] [int] NULL ,
	[ValuComp] [int] NULL ,
	[ItemMRPBillTm] [money] NULL ,
	[ItemCurBalQty] [money] NULL ,
	[lngAISrlNo] [int] NULL ,
	[SField1] [varchar] (256)   NULL ,
	[SField2] [varchar] (256)   NULL ,
	[SField3] [varchar] (256)   NULL ,
	[SField4] [varchar] (256)   NULL ,
	[SField5] [varchar] (256)   NULL ,
	[NField1] [int] NULL ,
	[NField2] [int] NULL ,
	[NField3] [int] NULL ,
	[NField4] [int] NULL ,
	[NField5] [int] NULL ,
	[DField1] [datetime] NULL ,
	[DField2] [datetime] NULL ,
	[DField3] [datetime] NULL ,
	[BField1] [bit] NULL ,
	[BField2] [bit] NULL ,
	[ItemLvlPriceFacId] [int] NULL ,
	[ItemLvlEDId] [int] NULL ,
	[DocEntPriceFactor] [money] NULL ,
	[stdTaxComp1Per] [money] NULL ,
	[DocEntED] [money] NULL ,
	[stdTaxComp2Per] [money] NULL ,
	[MerchId] [varchar] (16)   NULL ,
	[stdTaxComp3Per] [money] NULL ,
	[stdTaxComp4Per] [money] NULL ,
	[stdTaxComp5Per] [money] NULL ,
	[stdTaxComp1Inc] [bit] NULL ,
	[stdTaxComp2Inc] [bit] NULL ,
	[stdTaxComp3Inc] [bit] NULL ,
	[stdTaxComp4Inc] [bit] NULL ,
	[stdTaxComp5Inc] [bit] NULL ,
	[BefCurBalQty] [money] NULL ,
	[BefCurBalVal] [money] NULL ,
	[AftCurBalQty] [money] NULL ,
	[AftCurBalVal] [money] NULL ,
	[PromoCode] [varchar] (32)   NULL ,
	[PromoSlabSrlno] [int] NULL ,
	[PromoRemarks] [varchar] (256)   NULL ,
	[PromoType] [tinyint] NULL ,
	[PromoDefType] [tinyint] NULL ,
	[PromoIssueTrnType] [int] NULL ,
	[PromoIssueTrnCtrlNo] [int] NULL ,
	[PromoFwdLinkType] [int] NULL ,
	[PromoFwdLinkCtrlNo] [int] NULL ,
	[PromoItemLevelOfferVal] [money] NULL ,
	[PromoItemlLevelDiscDtls] [varchar] (128)   NULL ,
	[PromoItemGroup] [tinyint] NULL ,
	[PromoFlgItemLevel] [tinyint] NULL ,
	[PromoFlgBillLevel] [tinyint] NULL ,
	[PromoSetSrlNo] [int] NULL ,
	[PromoOfferItemType] [tinyint] NULL ,
	[ItemRemarks] [varchar] (256)   NULL ,
	[DiscRate] [money] NULL ,
	[ServicedQty] [money] NULL ,
	[LinkPOFromLoc] [varchar] (32)   NULL ,
	[LinkPoType] [int] NULL ,
	[LinkPoPrefix] [varchar] (50)   NULL ,
	[LinkPoNumber] [int] NULL ,
	[LinkPoEntrySrlno] [int] NULL ,
	[LinkPoEntrySubSrlno] [int] NULL ,
	[LinkPoDelDate] [datetime] NULL ,
	[ServiceLoc] [varchar] (32)   NULL ,
	[LinkEtTrntype] [int] NULL ,
	[LinkEtTrnCtrlno] [int] NULL ,
	[LinkEtDocSubSrlno] [int] NULL ,
	[TaxRevisionId] [int] NULL ,
	[ItemTaxFlag] [Int] NULL ,
	[DocEntAddonsTax] Money NULL,
	[DocRndOffValue] Money NULL,
	[TaxAV1] Money NULL,
	[TaxAV2] Money NULL,
	[TaxAV3] Money NULL,
	[TaxAV4] Money NULL,
	[TaxAV5] Money NULL,
	[ProdServInd] [Int] NULL ,
	[XS1] [varchar] (128) NULL,
	[XS2] [varchar] (128) NULL,
	[XS3] [varchar] (128) NULL,
	[XS4] [varchar] (128) NULL,
	[XS5] [varchar] (128) NULL,
	[XS6] [varchar] (128) NULL,
	[XS7] [varchar] (128) NULL,
	[XS8] [varchar] (128) NULL,
	[XI1] [int] NULL,
	[XI2] [int] NULL,
	[XI3] [int] NULL,
	[XI4] [int] NULL,
	[XM1] [money] NULL,
	[XM2] [money] NULL,
	[XM3] [money] NULL,
	[XM4] [money] NULL,
	[XD1] [DateTime] NULL,
	[XD2] [DateTime] NULL,
	[XD3] [DateTime] NULL,
	[XD4] [DateTime] NULL,
	[CS1] [varchar] (128) NULL,
	[CS2] [varchar] (128) NULL,
	[CS3] [varchar] (128) NULL,
	[CS4] [varchar] (128) NULL,
	[CS5] [varchar] (128) NULL,
	[CS6] [varchar] (128) NULL,
	[CS7] [varchar] (128) NULL,
	[CS8] [varchar] (128) NULL,
	[CI1] [int] NULL,
	[CI2] [int] NULL,
	[CI3] [int] NULL,
	[CI4] [int] NULL,
	[CM1] [money] NULL,
	[CM2] [money] NULL,
	[CM3] [money] NULL,
	[CM4] [money] NULL,
	[CD1] [DateTime] NULL,
	[CD2] [DateTime] NULL,
	[CD3] [DateTime] NULL,
	[CD4] [DateTime] NULL
) ON [PRIMARY]
