CREATE TABLE [dbo].[StkTrnHdr] (
	[TrnType] [int] NOT NULL ,
	[TrnCtrlNo] [int] NOT NULL ,
	[DocNoPrefix] [varchar] (8)   NULL ,
	[DocNo] [int] NULL ,
	[DocRsnCd] [varchar] (16)   NULL ,
	[DocDt] [datetime] NULL ,
	[DocTime] [datetime] NULL ,
	[DocStat] [varchar] (4)   NULL ,
	[PackCountDoc] [int] NULL ,
	[PackCountPhy] [int] NULL ,
	[PartyType] [int] NULL ,
	[PartyId] [varchar] (16)   NULL ,
	[PartyStkDocNo] [varchar] (32)   NULL ,
	[PartyStkDocDt] [datetime] NULL ,
	[OrdDocType] [int] NULL ,
	[OrdDocNoPrefix] [varchar] (8)   NULL ,
	[OrdDocNo] [int] NULL ,
	[OrdDocDt] [datetime] NULL ,
	[AccDocTyp] [int] NULL ,
	[AccDocNo] [varchar] (32)   NULL ,
	[AccDocDt] [datetime] NULL ,
	[TotDocValue] [money] NULL ,
	[TotDocDisc] [money] NULL ,
	[TotDocTax] [money] NULL ,
	[TotDocAddons] [money] NULL ,
	[TotDocDedns] [money] NULL ,
	[NetDocValue] [money] NULL ,
	[EnteredSizewise] [bit] NULL ,
	[TaxComp1] [money] NULL ,
	[TaxComp2] [money] NULL ,
	[TaxComp3] [money] NULL ,
	[TaxComp4] [money] NULL ,
	[TaxComp5] [money] NULL ,
	[FrwdRefTrnType] [int] NULL ,
	[FrwdRefCtrlNo] [int] NULL ,
	[BkwdRefTrnType] [int] NULL ,
	[BkwdRefCtrlNo] [int] NULL ,
	[DocVoidInd] [int] NULL ,
	[BilllvlDiscId] [varchar] (50)   NULL ,
	[BillPassInd] [int] NULL ,
	[VAUid] [varchar] (32)   NULL ,
	[VActr] [int] NULL ,
	[VATermId] [varchar] (32)   NULL ,
	[VACompCode] [varchar] (16)   NULL ,
	[DocRemarks] [varchar] (128)   NULL ,
	[TotalLineItems] [int] NULL ,
	[SField1] [varchar] (256)   NULL ,
	[SField2] [varchar] (256)   NULL ,
	[SField3] [varchar] (256)   NULL ,
	[SField4] [varchar] (256)   NULL ,
	[SField5] [varchar] (256)   NULL ,
	[NField1] [int] NULL ,
	[NField2] [int] NULL ,
	[NField3] [int] NULL ,
	[NField4] [int] NULL ,
	[NField5] [int] NULL ,
	[DField1] [datetime] NULL ,
	[DField2] [datetime] NULL ,
	[DField3] [datetime] NULL ,
	[BField1] [bit] NULL ,
	[BField2] [bit] NULL ,
	[ProdServInd] [varchar] (1)   NULL ,
	[TotDocPriceFactor] [money] NULL ,
	[TotDocED] [money] NULL ,
	[TotDocEntBefTaxAddons] [money] NULL ,
	[TotDocEntBefTaxDedns] [money] NULL ,
	[TotDocEntAftTaxAddons] [money] NULL ,
	[TotDocEntAftTaxDedns] [money] NULL ,
	[PromoCode] [varchar] (32)   NULL ,
	[PromoSlabSrlno] [int] NULL ,
	[PromoRemarks] [varchar] (256)   NULL ,
	[PromoType] [tinyint] NULL ,
	[PromoDefType] [tinyint] NULL ,
	[PromoIssueTrnType] [int] NULL ,
	[PromoIssueTrnCtrlNo] [int] NULL ,
	[PromoFwdLinkType] [int] NULL ,
	[PromoFwdLinkCtrlNo] [int] NULL ,
	[PromoBillLevelOfferVal] [money] NULL ,
	[PromoItemLevelOfferVal] [money] NULL ,
	[PromoItemLevelDiscVal] [money] NULL ,
	[PromoBillLevelDiscDtls] [varchar] (128)   NULL ,
	[ReasonCodeForCancel] [varchar] (50)   NULL ,
	[GenDiscReason] [varchar] (250)   NULL ,
	[LinkEtTrnType] [int] NULL ,
	[LinkEtTrnCtrlNo] [int] NULL ,
	[LinkPOVendor] [varchar] (16)   NULL ,
	[TotRndOffValue] Money NULL ,
	[TotDocAddonsTax] Money NULL,
	[SHOPERDBVER] [Int] NULL ,
	[XS1] [varchar] (128) NULL,
	[XS2] [varchar] (128) NULL,
	[XS3] [varchar] (128) NULL,
	[XS4] [varchar] (128) NULL,
	[XS5] [varchar] (128) NULL,
	[XS6] [varchar] (128) NULL,
	[XS7] [varchar] (128) NULL,
	[XS8] [varchar] (128) NULL,
	[XI1] [int] NULL,
	[XI2] [int] NULL,
	[XI3] [int] NULL,
	[XI4] [int] NULL,
	[XM1] [money] NULL,
	[XM2] [money] NULL,
	[XM3] [money] NULL,
	[XM4] [money] NULL,
	[XD1] [DateTime] NULL,
	[XD2] [DateTime] NULL,
	[XD3] [DateTime] NULL,
	[XD4] [DateTime] NULL,
	[CS1] [varchar] (128) NULL,
	[CS2] [varchar] (128) NULL,
	[CS3] [varchar] (128) NULL,
	[CS4] [varchar] (128) NULL,
	[CS5] [varchar] (128) NULL,
	[CS6] [varchar] (128) NULL,
	[CS7] [varchar] (128) NULL,
	[CS8] [varchar] (128) NULL,
	[CI1] [int] NULL,
	[CI2] [int] NULL,
	[CI3] [int] NULL,
	[CI4] [int] NULL,
	[CM1] [money] NULL,
	[CM2] [money] NULL,
	[CM3] [money] NULL,
	[CM4] [money] NULL,
	[CD1] [DateTime] NULL,
	[CD2] [DateTime] NULL,
	[CD3] [DateTime] NULL,
	[CD4] [DateTime] NULL
) ON [PRIMARY]
