/* ============================================================
 * PrimeSetu — Shoper9-Based Retail OS
 * Zero Cloud · Sovereign · AI-Governed
 * ============================================================
 * System Architect   :  Jawahar R Mallah
 * Organisation       :  AITDL Network
 * Project            :  PrimeSetu
 * © 2026 — All Rights Reserved
 * "Memory, Not Code."
 * ============================================================ */
// This file is auto-generated by Supabase CLI.
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_REF > src/types/database.ts
// DO NOT EDIT MANUALLY.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export interface Database {
  public: {
    Tables: {
      stores:     { Row: Store;     Insert: StoreInsert;     Update: StoreUpdate }
      users:      { Row: User;      Insert: UserInsert;      Update: UserUpdate }
      products:   { Row: Product;   Insert: ProductInsert;   Update: ProductUpdate }
      stock:      { Row: Stock;     Insert: StockInsert;     Update: StockUpdate }
      bills:      { Row: Bill;      Insert: BillInsert;      Update: BillUpdate }
      bill_items: { Row: BillItem;  Insert: BillItemInsert;  Update: BillItemUpdate }
      schemes:    { Row: Scheme;    Insert: SchemeInsert;    Update: SchemeUpdate }
      ledger:     { Row: Ledger;    Insert: LedgerInsert;    Update: LedgerUpdate }
      ai_outputs: { Row: AIOutput;  Insert: AIOutputInsert;  Update: AIOutputUpdate }
      sync_log:   { Row: SyncLog;   Insert: SyncLogInsert;   Update: SyncLogUpdate }
    }
    Views: {}
    Functions: {}
    Enums: {
      bill_status:   'draft' | 'confirmed' | 'cancelled'
      stock_status:  'ok' | 'low' | 'critical' | 'out'
      user_role:     'owner' | 'manager' | 'cashier' | 'viewer'
      scheme_type:   'flat' | 'percent' | 'bxgy' | 'combo'
      ledger_type:   'sale' | 'purchase' | 'payment' | 'receipt' | 'journal'
    }
  }
}

// ── Convenience row types ──────────────────────────────
export type Store        = { id: string; name: string; code: string; address: string; gstin: string; created_at: string }
export type StoreInsert  = Omit<Store, 'id' | 'created_at'>
export type StoreUpdate  = Partial<StoreInsert>

export type User        = { id: string; store_id: string; email: string; full_name: string; role: Database['public']['Enums']['user_role']; active: boolean; created_at: string }
export type UserInsert  = Omit<User, 'id' | 'created_at'>
export type UserUpdate  = Partial<UserInsert>

export type Product        = { id: string; store_id: string; name: string; sku: string; barcode: string | null; mrp: number; hsn: string; gst_percent: number; category: string; brand: string; unit: string; created_at: string }
export type ProductInsert  = Omit<Product, 'id' | 'created_at'>
export type ProductUpdate  = Partial<ProductInsert>

export type Stock        = { id: string; store_id: string; product_id: string; qty: number; reorder_level: number; status: Database['public']['Enums']['stock_status']; updated_at: string }
export type StockInsert  = Omit<Stock, 'id' | 'updated_at'>
export type StockUpdate  = Partial<StockInsert>

export type Bill        = { id: string; store_id: string; bill_no: string; bill_date: string; customer_name: string | null; customer_mobile: string | null; till_id: string; cashier_id: string; subtotal: number; discount: number; gst: number; total: number; status: Database['public']['Enums']['bill_status']; created_at: string }
export type BillInsert  = Omit<Bill, 'id' | 'created_at'>
export type BillUpdate  = Partial<BillInsert>

export type BillItem        = { id: string; bill_id: string; product_id: string; qty: number; mrp: number; discount: number; scheme_id: string | null; amount: number }
export type BillItemInsert  = Omit<BillItem, 'id'>
export type BillItemUpdate  = Partial<BillItemInsert>

export type Scheme        = { id: string; store_id: string; name: string; type: Database['public']['Enums']['scheme_type']; value: number; min_qty: number | null; active: boolean; starts_at: string; ends_at: string | null }
export type SchemeInsert  = Omit<Scheme, 'id'>
export type SchemeUpdate  = Partial<SchemeInsert>

export type Ledger        = { id: string; store_id: string; type: Database['public']['Enums']['ledger_type']; amount: number; party_name: string | null; ref_id: string | null; narration: string | null; entry_date: string; created_at: string }
export type LedgerInsert  = Omit<Ledger, 'id' | 'created_at'>
export type LedgerUpdate  = Partial<LedgerInsert>

export type AIOutput        = { id: string; store_id: string; prompt_hash: string; output: string; critic_score: number | null; loop_iterations: number; created_at: string }
export type AIOutputInsert  = Omit<AIOutput, 'id' | 'created_at'>
export type AIOutputUpdate  = Partial<AIOutputInsert>

export type SyncLog = {
  id: string
  packet_id: string
  packet_type: 'BILL' | 'RETURNS' | 'STOCK_ADJUST' | 'PO'
  payload: Json
  store_id: string
  created_at: string
}
export type SyncLogInsert = Omit<SyncLog, 'id' | 'created_at'>
export type SyncLogUpdate = Partial<SyncLogInsert>
