# ============================================================
# * SMRITI-OS - Shoper9-Based Retail OS
# * Zero Cloud . Sovereign . AI-Governed
# ============================================================
# * System Architect   :  Jawahar R Mallah
# * Organisation       :  AITDL Network
# * Project            :  SMRITI-OS
# * (c) 2026 - All Rights Reserved
# * "Memory, Not Code."
# ============================================================ #

import uuid
from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict, Any
from datetime import datetime

class PaymentModeDetail(BaseModel):
    mode: str
    amount: int = Field(..., description="Amount in paise (integer)")
    ref_no: Optional[str] = None

class BillItemCreate(BaseModel):
    # Legacy Shoper9 stockno (primary key for lookup)
    stock_no: Optional[str] = Field(None, description="Shoper9 stockno (preferred)")
    descr: Optional[str] = Field(None, description="Item description (denormalized)")
    # Retained for backward compatibility
    product_id: Optional[uuid.UUID] = Field(None, description="UUID (legacy, deprecated)")
    qty: float = Field(..., description="Quantity (decimal supported)")
    unit_price: int = Field(..., description="Unit price in paise (integer)")
    discount_per: int = Field(0, description="Discount percentage as integer")
    tax_per: int = Field(0, description="Tax percentage as integer")

class BillCreate(BaseModel):
    customer_mobile: Optional[str] = None
    items: List[BillItemCreate]
    payments: Optional[List[PaymentModeDetail]] = None
    type: str = "Sales" # Sales, SalesReturn
    till_id: Optional[int] = None
    cashier_id: Optional[uuid.UUID] = None
    shoper_recid: Optional[int] = None
    original_invoice_id: Optional[uuid.UUID] = None
    suspended_reason: Optional[str] = None

class BillResponse(BaseModel):
    status: str
    bill_number: Optional[str] = None
    transaction_id: uuid.UUID
    total: int = Field(..., description="Total amount in paise (integer)")

class SlipCreate(BaseModel):
    customer_mobile: Optional[str] = None
    items: List[BillItemCreate]

class SlipResponse(BaseModel):
    status: str
    slip_no: str
    slip_id: uuid.UUID
    total: int = Field(..., description="Total amount in paise (integer)")

class TransactionItemRead(BaseModel):
    id: uuid.UUID
    product_id: Optional[uuid.UUID] = None
    stock_no: Optional[str] = None
    qty: float
    mrp: int
    discount_per: int
    tax_amount: int
    net_amount: int
    # Enriched fields for UI
    code: Optional[str] = None
    name: Optional[str] = None
    brand: Optional[str] = None
    category: Optional[str] = None
    model_config = ConfigDict(from_attributes=True)

class TransactionRead(BaseModel):
    id: uuid.UUID
    bill_no: Optional[str] = None
    customer_id: Optional[uuid.UUID] = None
    type: str
    payments: Optional[Dict[str, Any]] = None
    subtotal: int
    discount_total: int
    tax_total: int
    net_payable: int
    cashier_id: Optional[uuid.UUID] = None
    till_id: Optional[int] = None
    shoper_recid: Optional[int] = None
    status: str
    created_at: datetime
    items: List[TransactionItemRead] = []
    model_config = ConfigDict(from_attributes=True)

class TransactionCreate(BaseModel):
    customer_mobile: Optional[str] = None
    items: List[BillItemCreate]
    payments: Optional[List[PaymentModeDetail]] = None
    type: str = "Sales"
    till_id: Optional[int] = None
    cashier_id: Optional[uuid.UUID] = None
    customer_id: Optional[uuid.UUID] = None
    salesman_id: Optional[str] = Field(None, description="ID or name of the sales personnel")
    bill_no: Optional[str] = Field(None, description="External bill number if generated by client")
    bill_discount: Optional[int] = Field(0, description="Additional bill-level discount in paise")
    shoper_recid: Optional[int] = None
    suspended_reason: Optional[str] = None
