import os

file_path = r"d:\IMP\GitHub\primesetu\backend\app\models\legacy_s9.py"

classes_str = """
# =========================================================================
# Purchase Order Tables (Added for Smriti Purchase Protocol v2.0)
# =========================================================================

class Purchordconfig(Base):
    __tablename__ = 'purchordconfig'
    classification: Mapped[str] = mapped_column(String(32), primary_key=True)
    selected: Mapped[bool] = mapped_column(Boolean, default=False)
    mandatory: Mapped[Optional[bool]] = mapped_column(Boolean)
    disporder: Mapped[Optional[int]] = mapped_column(Integer)
    vauid: Mapped[Optional[str]] = mapped_column(String(32))
    vactr: Mapped[Optional[int]] = mapped_column(Integer)
    vatermid: Mapped[Optional[str]] = mapped_column(String(32))
    vacompcode: Mapped[Optional[str]] = mapped_column(String(16))
    tenant_id: Mapped[str] = mapped_column(String, index=True, default="SYSTEM")

class Purchordhdr(Base):
    __tablename__ = 'purchordhdr'
    potype: Mapped[int] = mapped_column(Integer, primary_key=True, default=0)
    ponoprefix: Mapped[str] = mapped_column(String(8), primary_key=True)
    poctrlno: Mapped[int] = mapped_column(Integer, primary_key=True)
    supptype: Mapped[Optional[str]] = mapped_column(String(2))
    suppid: Mapped[Optional[str]] = mapped_column(String(16))
    podate: Mapped[Optional[datetime]] = mapped_column(DateTime)
    ordcurrency: Mapped[Optional[str]] = mapped_column(String(16))
    ordcurrencyval: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    convrate: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    loccurrencyval: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    deldate: Mapped[Optional[datetime]] = mapped_column(DateTime)
    shiptype: Mapped[Optional[str]] = mapped_column(String(16))
    transmode: Mapped[Optional[str]] = mapped_column(String(16))
    advanceper: Mapped[Optional[int]] = mapped_column(Integer, default=0)
    ordcurrencyadvval: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    loccurrencyadvval: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    creditdays: Mapped[Optional[int]] = mapped_column(Integer, default=0)
    isposizewise: Mapped[Optional[bool]] = mapped_column(Boolean, default=False)
    vauid: Mapped[Optional[str]] = mapped_column(String(32))
    vactr: Mapped[Optional[int]] = mapped_column(Integer, default=0)
    vatermid: Mapped[Optional[str]] = mapped_column(String(32))
    vacompcode: Mapped[Optional[str]] = mapped_column(String(16))
    shipmentaddr: Mapped[Optional[str]] = mapped_column(String(250))
    docremarks: Mapped[Optional[str]] = mapped_column(String(512))
    delperiodindays: Mapped[Optional[int]] = mapped_column(Integer)
    isconsignmentitemspo: Mapped[Optional[bool]] = mapped_column(Boolean)
    buyercode: Mapped[Optional[float]] = mapped_column(Float)
    sourcecompcd: Mapped[Optional[str]] = mapped_column(String(16))
    posource: Mapped[Optional[int]] = mapped_column(Integer)
    povendertype: Mapped[Optional[str]] = mapped_column(String(2))
    povendorid: Mapped[Optional[str]] = mapped_column(String(16))
    pobilltovendertype: Mapped[Optional[str]] = mapped_column(String(2))
    pobilltovendorid: Mapped[Optional[str]] = mapped_column(String(16))
    addonbeftaxhdrper: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    addonafttaxhdrper: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    deductbeftaxhdrper: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    deductafttaxhdrper: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    discountbeftaxhdrper: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    discountafttaxhdrper: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    dateinsert: Mapped[Optional[datetime]] = mapped_column(DateTime)
    lastmodifieddt: Mapped[Optional[datetime]] = mapped_column(DateTime)
    closuredate: Mapped[Optional[datetime]] = mapped_column(DateTime)
    closureremarks: Mapped[Optional[str]] = mapped_column(String(256))
    reopendatetime: Mapped[Optional[datetime]] = mapped_column(DateTime)
    reopenremarks: Mapped[Optional[str]] = mapped_column(String(256))
    shoperdbver: Mapped[Optional[int]] = mapped_column(Integer, default=730)
    tenant_id: Mapped[str] = mapped_column(String, index=True, default="SYSTEM")

class Purchorddtl(Base):
    __tablename__ = 'purchorddtl'
    potype: Mapped[int] = mapped_column(Integer, primary_key=True, default=0)
    ponoprefix: Mapped[str] = mapped_column(String(8), primary_key=True)
    poctrlno: Mapped[int] = mapped_column(Integer, primary_key=True)
    deliverylocation: Mapped[str] = mapped_column(String(16), primary_key=True, default='NA')
    entrysrlno: Mapped[int] = mapped_column(Integer, primary_key=True)
    entrysubsrlno: Mapped[int] = mapped_column(Integer, primary_key=True)
    podate: Mapped[Optional[datetime]] = mapped_column(DateTime)
    itemclass1: Mapped[Optional[str]] = mapped_column(String(50))
    itemclass2: Mapped[Optional[str]] = mapped_column(String(50))
    itemsubclass1: Mapped[Optional[str]] = mapped_column(String(50))
    itemsubclass2: Mapped[Optional[str]] = mapped_column(String(50))
    itemsize: Mapped[Optional[str]] = mapped_column(String(50))
    stockno: Mapped[Optional[str]] = mapped_column(String(32))
    descr: Mapped[Optional[str]] = mapped_column(String(256))
    purchordqty: Mapped[Optional[float]] = mapped_column(Float, default=0)
    purchordrate: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    pocurrency: Mapped[Optional[str]] = mapped_column(String(16))
    convrate: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    deldate: Mapped[Optional[datetime]] = mapped_column(DateTime)
    rcvdqty: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    planadhocind: Mapped[Optional[str]] = mapped_column(String(16))
    poorgqty: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    poind: Mapped[Optional[str]] = mapped_column(String(1))
    vauid: Mapped[Optional[str]] = mapped_column(String(32))
    vactr: Mapped[Optional[int]] = mapped_column(Integer, default=0)
    vatermid: Mapped[Optional[str]] = mapped_column(String(32))
    vacompcode: Mapped[Optional[str]] = mapped_column(String(16))
    orderedmtrs: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    cancelqty: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    holdqty: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    buyercode: Mapped[Optional[float]] = mapped_column(Float)
    posource: Mapped[Optional[int]] = mapped_column(Integer)
    sourcecompcd: Mapped[Optional[str]] = mapped_column(String(16))
    poattributelevel: Mapped[Optional[str]] = mapped_column(String(64))
    poappanlcount: Mapped[Optional[int]] = mapped_column(Integer)
    line_remarks: Mapped[Optional[str]] = mapped_column("lineremarks", String(64))
    doclinegrossvalue: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    salestaxper: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    salestaxamt: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    doclinenetvalue: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4))
    poclosureflag: Mapped[Optional[int]] = mapped_column(Integer)
    poconsolflag: Mapped[Optional[int]] = mapped_column(Integer)
    dateinsert: Mapped[Optional[datetime]] = mapped_column(DateTime)
    lastmodifieddt: Mapped[Optional[datetime]] = mapped_column(DateTime)
    tenant_id: Mapped[str] = mapped_column(String, index=True, default="SYSTEM")

class Purchordtrl(Base):
    __tablename__ = 'purchordtrl'
    ponoprefix: Mapped[str] = mapped_column(String(8), primary_key=True)
    poctrlno: Mapped[int] = mapped_column(Integer, primary_key=True)
    entrysrlno: Mapped[int] = mapped_column(Integer, primary_key=True)
    entrytype: Mapped[Optional[str]] = mapped_column(String(2))
    entryid: Mapped[Optional[str]] = mapped_column(String(16))
    entryapponfrom: Mapped[Optional[int]] = mapped_column(Integer, default=0)
    entryapponto: Mapped[Optional[int]] = mapped_column(Integer, default=0)
    entrydesc: Mapped[Optional[str]] = mapped_column(String(50))
    entryper: Mapped[Optional[float]] = mapped_column(Float, default=0)
    ordcurrencyamt: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    convrate: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    loccurrencyamt: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    vauid: Mapped[Optional[str]] = mapped_column(String(32))
    vactr: Mapped[Optional[int]] = mapped_column(Integer, default=0)
    vatermid: Mapped[Optional[str]] = mapped_column(String(32))
    vacompcode: Mapped[Optional[str]] = mapped_column(String(16))
    tenant_id: Mapped[str] = mapped_column(String, index=True, default="SYSTEM")

class Purchplan(Base):
    __tablename__ = 'purchplan'
    deptsrlno: Mapped[int] = mapped_column(Integer, primary_key=True, default=0)
    merchsrlno: Mapped[int] = mapped_column(Integer, primary_key=True, default=0)
    entrysrlno: Mapped[int] = mapped_column(Integer, primary_key=True, default=0)
    startdt: Mapped[Optional[datetime]] = mapped_column(DateTime)
    enddt: Mapped[Optional[datetime]] = mapped_column(DateTime)
    planby: Mapped[Optional[str]] = mapped_column(String(16))
    planref: Mapped[Optional[str]] = mapped_column(String(50))
    deptname: Mapped[Optional[str]] = mapped_column(String(50))
    merchname: Mapped[Optional[str]] = mapped_column(String(50))
    storatio: Mapped[Optional[float]] = mapped_column(Float, default=0)
    superclass1: Mapped[Optional[str]] = mapped_column(String(16))
    superclass2: Mapped[Optional[str]] = mapped_column(String(16))
    itemclass1: Mapped[Optional[str]] = mapped_column(String(16))
    itemclass2: Mapped[Optional[str]] = mapped_column(String(16))
    regularind: Mapped[Optional[str]] = mapped_column(String(2))
    opstkqty: Mapped[Optional[float]] = mapped_column(Float, default=0)
    opstkval: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    purchqty: Mapped[Optional[float]] = mapped_column(Float, default=0)
    purchval: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    saleqty: Mapped[Optional[float]] = mapped_column(Float, default=0)
    salecost: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    clstkqty: Mapped[Optional[float]] = mapped_column(Float, default=0)
    clstkval: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    saleval: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 4), default=0)
    vauid: Mapped[Optional[str]] = mapped_column(String(32))
    vactr: Mapped[Optional[int]] = mapped_column(Integer, default=0)
    vatermid: Mapped[Optional[str]] = mapped_column(String(32))
    vacompcode: Mapped[Optional[str]] = mapped_column(String(16))
    tenant_id: Mapped[str] = mapped_column(String, index=True, default="SYSTEM")
"""

with open(file_path, "a", encoding="utf-8") as f:
    f.write(classes_str)
print("Added Purchase Order tables to legacy_s9.py!")
