
CREATE PROCEDURE [dbo].[pGET_LAST_QUARTER] @From_Dt CHAR(10) OUTPUT,@To_Dt CHAR(10) OUTPUT       
AS        
BEGIN       
DECLARE @FISCAL_DATE DATETIME       
DECLARE @MONTH VARCHAR(10)
DECLARE @REFDATE DATETIME
DECLARE @CUR_DATE DATETIME       
SET @MONTH=(SELECT TXT FROM SYSPARAM WHERE PARAMCODE LIKE 'FISCALMONTH')   
SET @REFDATE=(SELECT CONVERT(DATETIME, DT, 121) FROM SYSPARAM WHERE PARAMCODE = 'SHOPERSYSDT')
IF MONTH(@REFDATE)< MONTH(@MONTH +' '+ CAST(YEAR(@REFDATE)-1  AS CHAR(15)))       
 SET @FISCAL_DATE=(SELECT @MONTH +' '+ CAST(YEAR(@REFDATE)-1  AS CHAR(15)))        
ELSE      
 SET @FISCAL_DATE= (SELECT @MONTH +' '+ CAST(YEAR(@REFDATE)  AS CHAR(15)))       
    
SET @CUR_DATE=(SELECT @REFDATE)       
    
IF CAST(CONVERT(CHAR(10),@CUR_DATE,103) AS DATETIME) BETWEEN CAST(CONVERT(CHAR(10),@FISCAL_DATE,103) AS DATETIME) AND CAST(CONVERT(CHAR(10),DATEADD(DD,-1,DATEADD(MM,3,@FISCAL_DATE)),103) AS DATETIME)  
BEGIN       
 SET @From_Dt=(SELECT CONVERT(CHAR(8),DATEADD(MM,-3,@FISCAL_DATE),3))       
 SET @To_Dt=(SELECT CONVERT(CHAR(8),@FISCAL_DATE-1,3))     
END       
ELSE        
    
 IF CAST(CONVERT(CHAR(10),@CUR_DATE,103) AS DATETIME) BETWEEN CAST(CONVERT(CHAR(10),DATEADD(MM,3,@FISCAL_DATE),103) AS DATETIME) AND CAST(CONVERT(CHAR(10),DATEADD(DD,-1,DATEADD(MM,6,@FISCAL_DATE)),103) AS DATETIME)  
 BEGIN       
  SET @From_Dt=(SELECT CONVERT(CHAR(8),@FISCAL_DATE,3))       
  SET @To_Dt=(SELECT CONVERT(CHAR(8),DATEADD(DD,-1,DATEADD(MM,3,@FISCAL_DATE)),3))         
 END       
 ELSE        
    
  IF CAST(CONVERT(CHAR(10),@CUR_DATE,103) AS DATETIME) BETWEEN CAST(CONVERT(CHAR(10),DATEADD(MM,6,@FISCAL_DATE),103) AS DATETIME) AND CAST(CONVERT(CHAR(10),DATEADD(DD,-1,DATEADD(MM,9,@FISCAL_DATE)),103) AS DATETIME)  
  BEGIN       
   SET @From_Dt=(SELECT CONVERT(CHAR(8),DATEADD(MM,3,@FISCAL_DATE),3))       
   SET @To_Dt=(SELECT CONVERT(CHAR(8),DATEADD(DD,-1,DATEADD(MM,6,@FISCAL_DATE)),3))          
  END       
  ELSE       
     
   IF CAST(CONVERT(CHAR(10),@CUR_DATE,103) AS DATETIME) BETWEEN CAST(CONVERT(CHAR(10),DATEADD(MM,9,@FISCAL_DATE),103) AS DATETIME) AND CAST(CONVERT(CHAR(10),DATEADD(DD,-1,DATEADD(MM,12,@FISCAL_DATE)),103) AS DATETIME)      
   BEGIN       
   SET @From_Dt=(SELECT CONVERT(CHAR(8),DATEADD(MM,6,@FISCAL_DATE),3))       
   SET @To_Dt=(SELECT CONVERT(CHAR(8),DATEADD(DD,-1,DATEADD(MM,9,@FISCAL_DATE)),3))         
   END       
          
   ELSE       
   BEGIN       
    SET @From_Dt=(SELECT CONVERT(CHAR(8),DATEADD(MM,-6,@FISCAL_DATE),3))       
    SET @To_Dt=(SELECT CONVERT(CHAR(8),DATEADD(DD,-1,DATEADD(MM,-3,@FISCAL_DATE)),3))           
   END       
         
SELECT @From_Dt,@To_Dt       
END 
