"""
SMRITI-OS - Multi-Tenant PK Audit
===================================
Finds ALL tables in s9 schema where:
  - tenant_id column EXISTS
  - BUT tenant_id is NOT part of the Primary Key
  => These tables can have duplicates!

Also outputs the migration SQL to fix them all.
"""
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

import asyncio
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy import text

PG_URL = 'postgresql+asyncpg://postgres:MSba108682%21%40@127.0.0.1:5434/smriti_local'
SCHEMA = 's9'

async def main():
    engine = create_async_engine(PG_URL)
    async with engine.connect() as conn:

        # --- 1. Get all tables that have a tenant_id column
        r = await conn.execute(text(f"""
            SELECT table_name
            FROM information_schema.columns
            WHERE table_schema = '{SCHEMA}'
              AND column_name = 'tenant_id'
            ORDER BY table_name
        """))
        tables_with_tenant = [row[0] for row in r.fetchall()]
        print(f"\n[SCAN] Tables with tenant_id column: {len(tables_with_tenant)}")

        # --- 2. For each table, check if tenant_id is in PK
        needs_fix   = []   # tenant_id exists but NOT in PK
        already_ok  = []   # tenant_id is part of PK
        no_pk       = []   # no PK at all

        for table in tables_with_tenant:
            r = await conn.execute(text(f"""
                SELECT kcu.column_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                   AND tc.table_schema    = kcu.table_schema
                WHERE tc.constraint_type = 'PRIMARY KEY'
                  AND tc.table_schema    = '{SCHEMA}'
                  AND tc.table_name      = '{table}'
                ORDER BY kcu.ordinal_position
            """))
            pk_cols = [row[0] for row in r.fetchall()]

            if not pk_cols:
                no_pk.append(table)
            elif 'tenant_id' in pk_cols:
                already_ok.append((table, pk_cols))
            else:
                needs_fix.append((table, pk_cols))

        # --- 3. Print results
        print(f"\n{'='*65}")
        print(f"  SUMMARY")
        print(f"{'='*65}")
        print(f"  Tables with tenant_id:           {len(tables_with_tenant)}")
        print(f"  Already have tenant_id in PK:    {len(already_ok)}")
        print(f"  [NEEDS FIX] tenant_id NOT in PK: {len(needs_fix)}")
        print(f"  No PK at all:                    {len(no_pk)}")

        if already_ok:
            print(f"\n[OK] Tables Already Correct:")
            for t, pk in already_ok:
                print(f"     {t:<45} PK={pk}")

        if no_pk:
            print(f"\n[WARN] Tables with NO Primary Key:")
            for t in no_pk:
                print(f"     {t}")

        if needs_fix:
            print(f"\n[NEEDS FIX] Tables where tenant_id must be added to PK:")
            print(f"  {'Table':<45} {'Current PK'}")
            print(f"  {'-'*45} {'-'*30}")
            for t, pk in needs_fix:
                print(f"  {t:<45} {pk}")

        # --- 4. Generate Migration SQL
        print(f"\n\n{'='*65}")
        print(f"  GENERATED MIGRATION SQL")
        print(f"{'='*65}")
        print(f"-- Auto-generated by audit_tenant_pk.py")
        print(f"-- Adds tenant_id to Primary Key for {len(needs_fix)} tables")
        print(f"-- Run inside a transaction!\n")
        print(f"BEGIN;\n")

        for table, old_pk in needs_fix:
            # Get constraint name
            r = await conn.execute(text(f"""
                SELECT tc.constraint_name
                FROM information_schema.table_constraints tc
                WHERE tc.constraint_type = 'PRIMARY KEY'
                  AND tc.table_schema    = '{SCHEMA}'
                  AND tc.table_name      = '{table}'
            """))
            row = r.fetchone()
            constraint_name = row[0] if row else f"{table}_pkey"
            new_pk = old_pk + ['tenant_id']
            new_pk_str = ', '.join(new_pk)

            print(f"-- Table: {table}")
            print(f"-- Old PK: {old_pk}")
            print(f"-- New PK: {new_pk}")
            print(f"ALTER TABLE {SCHEMA}.{table} DROP CONSTRAINT {constraint_name};")
            print(f"ALTER TABLE {SCHEMA}.{table} ADD CONSTRAINT {constraint_name} PRIMARY KEY ({new_pk_str});")
            print()

        print(f"COMMIT;")
        print(f"\n-- End of migration")

    await engine.dispose()

asyncio.run(main())
