# ============================================================
# SMRITI-OS - Shoper9-Based Retail OS
# Zero Cloud . Sovereign . AI-Governed
# ============================================================
# System Architect : Jawahar R Mallah
# Organisation     : AITDL Network
# Project          : SMRITI-OS
# (c) 2026 - All Rights Reserved
# "Memory, Not Code."
# ============================================================

"""
security.py - JWT verification & RBAC dependency

Two operational modes:
  CLOUD / SOVEREIGN -> Supabase JWT (HS256 or ES256)
  LOCAL_POSTGRES    -> Local JWT signed with LOCAL_JWT_SECRET

[R1-A] EC JWK is no longer hardcoded. It is read from settings.supabase_jwk_json
       (env var SUPABASE_JWK_JSON). This prevents key material from being committed
       to source control.

[R1-B] LOCAL_POSTGRES mode no longer bypasses auth entirely. Tokens must be valid
       JWTs signed with LOCAL_JWT_SECRET. This ensures cashier identity and RBAC
       enforcement in offline/LAN node deployments.
       Issue tokens via POST /api/v1/auth/local-login.

Usage in any route:
    from app.core.security import require_auth, require_role

    @app.get("/api/v1/products")
    async def list_products(current_user: CurrentUser = Depends(require_auth)):
        ...

    @app.delete("/api/v1/products/{id}")
    async def delete_product(product_id: int, current_user: CurrentUser = Depends(require_role("manager"))):
        ...
"""

import os
import secrets
import jwt
from dataclasses import dataclass
from typing import Optional
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from app.core.config import settings
from app.core.database import get_db
from sqlalchemy.ext.asyncio import AsyncSession
import logging

logger = logging.getLogger("smriti.security")

# .. Bearer token extractor ....................................................
_bearer = HTTPBearer(auto_error=True)
_bearer_optional = HTTPBearer(auto_error=False)  # returns None instead of 401

# -- [R1-B] Local JWT secret resolution ------------------------------------------
# In LOCAL_POSTGRES mode, the system uses locally-issued JWTs signed with
# LOCAL_JWT_SECRET instead of Supabase tokens. This ensures cashier identity
# and RBAC enforcement even when the node is fully offline.
#
# Priority: settings.local_jwt_secret (env LOCAL_JWT_SECRET) ->
#           auto-generated ephemeral secret (logged once, not persistent).
#
# For production nodes: set LOCAL_JWT_SECRET in .env (generated by setup wizard).

def _resolve_local_secret() -> str:
    if settings.local_jwt_secret:
        return settings.local_jwt_secret
    # Not configured: generate an ephemeral secret for this process lifetime.
    # Tokens issued survive only until the next server restart.
    # Operators MUST set LOCAL_JWT_SECRET in .env for production continuity.
    ephemeral = secrets.token_hex(32)
    logger.warning(
        "[SMRITI-OS] LOCAL_JWT_SECRET is not set in .env. "
        "Using an ephemeral secret — tokens will be invalidated on server restart. "
        "Run the setup wizard or set LOCAL_JWT_SECRET in .env to fix this."
    )
    return ephemeral


# Resolved once at import time for this process lifetime.
_LOCAL_JWT_SECRET: str = _resolve_local_secret()


# .. Typed user context ........................................................
@dataclass
class CurrentUser:
    user_id: str        # Supabase auth.users.id (UUID) or local user ID
    store_id: str       # From token metadata
    email: str
    role: str           # cashier | manager | admin
    tenant_id: str = "SYSTEM"
    full_name: Optional[str] = None

    @property
    def id(self) -> str:
        """Alias for compatibility with legacy routers."""
        return self.user_id


# -- [R1-A] EC JWK loader --------------------------------------------------------
# The EC JWK (x, y coordinates for P-256) is no longer hardcoded in source.
# Set SUPABASE_JWK_JSON in your .env as the full JWK JSON string.
# Example:
#   SUPABASE_JWK_JSON={"kty":"EC","crv":"P-256","x":"abc...","y":"def...","alg":"ES256"}
#
# If not set, ES256 tokens are rejected with a clear error message.

def _load_es256_key():
    """Load EC verification key from SUPABASE_JWK_JSON env var. Returns None if not set."""
    jwk_json = settings.supabase_jwk_json
    if not jwk_json:
        logger.warning(
            "[SMRITI-OS] SUPABASE_JWK_JSON is not set. "
            "ES256 token verification is disabled — ES256 tokens will be rejected."
        )
        return None
    try:
        from jwt.algorithms import ECAlgorithm
        key = ECAlgorithm.from_jwk(jwk_json)
        logger.info("[SMRITI-OS] ES256 JWK loaded successfully from SUPABASE_JWK_JSON.")
        return key
    except Exception as exc:
        logger.error(
            f"[SMRITI-OS] Failed to load ES256 JWK from SUPABASE_JWK_JSON: {exc}. "
            "ES256 verification disabled."
        )
        return None


# Loaded once at import time.
_ES256_VERIFICATION_KEY = _load_es256_key()


# .. Core JWT verifier .........................................................
def _decode_token(token: str, *, local_mode: bool = False) -> dict:
    """
    Decode and verify a JWT.

    local_mode=True:  verifies against LOCAL_JWT_SECRET (offline/LAN node tokens).
    local_mode=False: verifies against Supabase secrets (HS256 or ES256).
    """
    if local_mode:
        # [R1-B] Local node token path — signed by this node's LOCAL_JWT_SECRET.
        try:
            payload = jwt.decode(
                token,
                _LOCAL_JWT_SECRET,
                algorithms=["HS256"],
                options={"verify_exp": True},
            )
            return payload
        except jwt.ExpiredSignatureError:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="[SMRITI-OS] Local session token has expired. Please log in again.",
                headers={"WWW-Authenticate": "Bearer"},
            )
        except jwt.InvalidTokenError as exc:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail=f"[SMRITI-OS] Invalid local session token: {exc}",
                headers={"WWW-Authenticate": "Bearer"},
            )

    # Cloud / Sovereign path — Supabase JWT
    secret = settings.supabase_jwt_secret or os.environ.get("SUPABASE_JWT_SECRET") or settings.jwt_secret
    if not secret:
        raise RuntimeError("[SMRITI-OS] SUPABASE_JWT_SECRET is not set in environment.")

    try:
        header = jwt.get_unverified_header(token)
        alg = header.get("alg", "HS256")
        kid = header.get("kid")
        logger.debug(f"[SMRITI-OS] Auth pulse — Algorithm: {alg}, KID: {kid}")

        if alg == "ES256":
            # [R1-A] Use key loaded from env, not hardcoded source material.
            if _ES256_VERIFICATION_KEY is None:
                raise HTTPException(
                    status_code=status.HTTP_401_UNAUTHORIZED,
                    detail=(
                        "[SMRITI-OS] ES256 token received but SUPABASE_JWK_JSON is not configured. "
                        "Set SUPABASE_JWK_JSON in .env to enable ES256 verification."
                    ),
                )
            verification_key = _ES256_VERIFICATION_KEY
        else:
            verification_key = secret

        payload = jwt.decode(
            token,
            verification_key,
            algorithms=["HS256", "ES256"],
            audience="authenticated",
            options={
                "verify_exp": True,
                "verify_aud": True,
                "verify_iss": False,  # Supabase issuers vary by project ref
            },
        )
        return payload

    except jwt.ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="[SMRITI-OS] Token has expired. Please log in again.",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except jwt.InvalidTokenError as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"[SMRITI-OS] Invalid token ({alg}): {exc}",
            headers={"WWW-Authenticate": "Bearer"},
        )


def _build_user(payload: dict) -> CurrentUser:
    """Extract a typed CurrentUser from a decoded JWT payload.

    Supports two payload shapes:
      - Supabase: user_metadata.store_id, user_metadata.role, user_metadata.full_name
      - Local JWT: store_id, role, full_name at top level
    """
    meta = payload.get("user_metadata") or {}

    user_id   = payload.get("sub")
    store_id  = meta.get("store_id") or payload.get("store_id")
    tenant_id = meta.get("tenant_id") or payload.get("tenant_id", "SYSTEM")

    if not user_id:
        raise HTTPException(status_code=401, detail="[SMRITI-OS] Token missing 'sub'.")
    if not store_id:
        # Development / single-store fallback.
        store_id = "11"

    return CurrentUser(
        user_id=user_id,
        store_id=store_id,
        email=payload.get("email", ""),
        role=meta.get("role") or payload.get("role", "cashier"),
        tenant_id=tenant_id,
        full_name=meta.get("full_name") or payload.get("full_name"),
    )


# .. FastAPI dependencies ......................................................
async def require_auth(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(_bearer_optional),
    db: AsyncSession = Depends(get_db)
) -> CurrentUser:
    """
    Dependency: any authenticated user. Raises 401 if token is missing/invalid.

    [R1-B] LOCAL_POSTGRES mode no longer bypasses authentication.
    In LOCAL_POSTGRES mode, tokens are validated against LOCAL_JWT_SECRET.
    In CLOUD/SOVEREIGN mode, tokens are validated against Supabase JWT secret.
    """
    if not credentials:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="[SMRITI-OS] Authentication credentials missing.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    token = credentials.credentials
    is_local = settings.storage_mode == "LOCAL_POSTGRES"
    payload = _decode_token(token, local_mode=is_local)

    try:
        return _build_user(payload)
    except HTTPException as e:
        if e.status_code == 403 and not is_local:
            # Cloud mode: store_id missing from token metadata — try DB lookup.
            user_id_str = payload.get("sub")
            if not user_id_str:
                raise e

            from app.models import User
            from sqlalchemy import select
            import uuid

            try:
                user_uuid = uuid.UUID(user_id_str)
                stmt = select(User).where(User.id == user_uuid)
                result = await db.execute(stmt)
                user_obj = result.scalar_one_or_none()

                if user_obj:
                    logger.info(
                        f"[SMRITI-OS] Security: Resolved store_id '{user_obj.store_id}' "
                        f"from DB for user {user_id_str}"
                    )
                    return CurrentUser(
                        user_id=user_id_str,
                        store_id=user_obj.store_id,
                        email=user_obj.email,
                        role=user_obj.role,
                        tenant_id=user_obj.tenant_id,
                        full_name=user_obj.full_name
                    )
            except Exception as db_err:
                logger.error(
                    f"[SMRITI-OS] Security: DB lookup failed for {user_id_str}: {db_err}"
                )

        raise e


def require_role(*allowed_roles: str):
    """
    Dependency factory: only users whose role is in allowed_roles may proceed.

    Example:
        Depends(require_role("manager", "admin"))
    """
    async def _check(current_user: CurrentUser = Depends(require_auth)) -> CurrentUser:
        if current_user.role not in allowed_roles:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=(
                    f"[SMRITI-OS] Access denied. "
                    f"Required: {allowed_roles}, you have: '{current_user.role}'."
                ),
            )
        return current_user
    return _check


# .. Role aliases (convenience) ................................................
require_cashier = require_auth                           # any logged-in user
require_manager = require_role("manager", "admin")
require_admin   = require_role("admin")

# .. Optional auth (returns None when no token — for public endpoints) ........
async def optional_auth(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(_bearer_optional),
    db: AsyncSession = Depends(get_db)
) -> Optional[CurrentUser]:
    """Returns CurrentUser if a valid Bearer token is present, else None."""
    if not credentials:
        return None
    try:
        return await require_auth(credentials, db)
    except HTTPException:
        return None

# .. Phase 2 Legacy Aliases ...................................................
UserContext = CurrentUser
get_current_user = optional_auth   # menu.py uses this — optional by default
verify_role = require_role
